# Generated by Django 5.0.2 on 2024-04-13 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('product_name', models.CharField(max_length=100, null=True)),
                ('product_section', models.CharField(blank=True, choices=[('M', 'Mens'), ('F', 'Womens'), ('C', 'Children')], max_length=20)),
                ('features', models.TextField(blank=True)),
                ('size1', models.CharField(blank=True, max_length=3)),
                ('size2', models.CharField(blank=True, max_length=3)),
                ('size3', models.CharField(blank=True, max_length=3)),
                ('size4', models.CharField(blank=True, max_length=3)),
                ('price', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('qty', models.IntegerField(null=True)),
                ('description', models.TextField(blank=True)),
                ('photo1', models.ImageField(blank=True, upload_to='product_images/')),
                ('photo2', models.ImageField(blank=True, upload_to='product_images/')),
                ('photo3', models.ImageField(blank=True, upload_to='product_images/')),
                ('photo4', models.ImageField(blank=True, upload_to='product_images/')),
                ('discount', models.IntegerField(default=1)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Shiping', 'Shiping'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Deliverd'), ('Canceled', 'Canceled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Addtocart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
    ]
