# Generated by Django 5.0.4 on 2024-04-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phonenumber',
            field=models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=10),
        ),
    ]
