# Generated by Django 5.0.4 on 2024-04-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_address_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phonenumber',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=10),
        ),
    ]
