# Generated by Django 5.0.4 on 2024-05-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_addtocart_is_paid_addtocart_rozorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='addresssid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
