# Generated by Django 5.0.4 on 2024-05-04 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_addtocart_addresssid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='addresssid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.address'),
        ),
    ]
